# Configure NGINX for TLSv1.2 or TLSv1.3 only

events {}

http {
	server {
		listen 443 ssl;
		server_name aarponen.42.fr;

		ssl_certificate /etc/nginx/ssl/server.crt;
		ssl_certificate_key /etc/nginx/ssl/server.key;

		ssl_protocols TLSv1.2 TLSv1.3;

		root /var/www/html;
		index index.php index.html;

		# First attempt to serve request as file, then as directory, then fall back to displaying a 404.
		location / {
			try_files $uri $uri/ /index.php?$args;
		}


		# pass the PHP scripts to FastCGI server listening on wordpress:9000
		location ~ \.php$ {
			include fastcgi.conf;
			fastcgi_pass wordpress:9000;
		}
	}
}
