
# Run the following commands to check your Docker and Docker Compose versions:
# docker --version
# docker compose version
# If you're running Docker Engine 20.10+ and Docker Compose v2.0+, you can safely omit the version field.

# version: '3.8'

services:
 nginx:
  build: ./requirements/nginx
  image: nginx
  ports:
   - "443:443"
  restart: unless-stopped
  depends_on:
   - wordpress
  volumes:
   - wordpress:/var/www/html
  healthcheck:
   test: ["CMD", "curl", "-kf", "https://localhost", "--insecure", "-H", "Host: aarponen.42.fr"]
   interval: 10s
   timeout: 3s
   retries: 3
  networks:
   - private_net

 mariadb:
  build: ./requirements/mariadb
  image: mariadb
  ports:
   - "3306:3306"
  restart: unless-stopped
  env_file:
   - .env
  environment:
   MARIADB_PASSWORD_FILE: /run/secrets/db_password
   MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
  secrets:
   - db_password
   - db_root_password
  volumes:
   - database:/var/lib/mysql
  healthcheck:
   test: ["CMD", "/usr/local/bin/healthcheck.sh"]
   interval: 10s
   timeout: 5s
   retries: 3
  networks:
   - private_net

 wordpress:
  build: ./requirements/wordpress
  image: wordpress
  depends_on:
   - mariadb
  restart: unless-stopped
  env_file:
   - .env
  environment:
    WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_pw
    WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wp_user_pw
  secrets:
   - db_password
   - wp_admin_pw
   - wp_user_pw
  volumes:
   - wordpress:/var/www/html
  healthcheck:
   test: ["CMD", "php-fpm7.4", "-t"]
   interval: 10s
   timeout: 3s
   retries: 3
  networks:
   - private_net

volumes:
 database:
  driver: local
  driver_opts:
   type: none
   device: ${HOME}/data/database
   o: bind
 wordpress:
  driver: local
  driver_opts:
   type: none
   device: ${HOME}/data/html
   o: bind

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_pw:
    file: ../secrets/wp_admin_pw.txt
  wp_user_pw:
    file: ../secrets/wp_user_pw.txt

networks:
  private_net:
   driver: bridge